//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLMSGroup2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PLMSEntities : DbContext
    {
        public PLMSEntities()
            : base("name=PLMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<loan_app_or_rej> loan_app_or_rej { get; set; }
        public virtual DbSet<loan_application> loan_application { get; set; }
        public virtual DbSet<loan_officer_assign> loan_officer_assign { get; set; }
        public virtual DbSet<officer> officers { get; set; }
        public virtual DbSet<registration> registrations { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<registration_remark> registration_remark { get; set; }
    }
}
