//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLMSGroup2
{
    using System;
    using System.Collections.Generic;
    
    public partial class loan_officer_assign
    {
        public int id { get; set; }
        public int application_id { get; set; }
        public int officer_id { get; set; }
    
        public virtual loan_application loan_application { get; set; }
        public virtual officer officer { get; set; }
    }
}
