//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLMSGroup2
{
    using System;
    using System.Collections.Generic;
    
    public partial class loan_application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public loan_application()
        {
            this.loan_app_or_rej = new HashSet<loan_app_or_rej>();
            this.loan_officer_assign = new HashSet<loan_officer_assign>();
        }
    
        public int application_id { get; set; }
        public string name { get; set; }
        public string email_id { get; set; }
        public string gender { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public int age { get; set; }
        public string contact_no { get; set; }
        public string address { get; set; }
        public string pan_no { get; set; }
        public decimal loan_amount { get; set; }
        public decimal monthly_income { get; set; }
        public string company_name { get; set; }
        public string designation { get; set; }
        public string office_address { get; set; }
        public string office_contact_no { get; set; }
        public string office_email { get; set; }
        public bool existing_loan { get; set; }
        public byte[] photo { get; set; }
        public byte[] address_document { get; set; }
        public string status { get; set; }
        public int reg_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<loan_app_or_rej> loan_app_or_rej { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<loan_officer_assign> loan_officer_assign { get; set; }
        public virtual registration registration { get; set; }
    }
}
