//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLMSGroup2
{
    using System;
    using System.Collections.Generic;
    
    public partial class officer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public officer()
        {
            this.loan_officer_assign = new HashSet<loan_officer_assign>();
        }
    
        public int officer_id { get; set; }
        public int role_id { get; set; }
        public string name { get; set; }
        public string email_id { get; set; }
        public string contact_no { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<loan_officer_assign> loan_officer_assign { get; set; }
        public virtual role role { get; set; }
    }
}
